In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000

In [5]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7874, 5452, 4540, 1835],
 [7874, 5452, 4540, 8561],
 [7874, 7520, 4540, 8877],
 [4009, 3115, 3955, 7595, 8352],
 [4009, 3115, 3955, 7595, 4452],
 [8029, 7874, 4868, 4540, 5372],
 [8598, 4624, 9817, 7595]]

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7874 5452 4540 1835]
 [   0    0    0    0 7874 5452 4540 8561]
 [   0    0    0    0 7874 7520 4540 8877]
 [   0    0    0 4009 3115 3955 7595 8352]
 [   0    0    0 4009 3115 3955 7595 4452]
 [   0    0    0 8029 7874 4868 4540 5372]
 [   0    0    0    0 8598 4624 9817 7595]]


In [9]:
dim=10

In [21]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')
model.build(input_shape=(None, sent_length))


In [22]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step


array([[[-0.04248479,  0.02341903, -0.01011783,  0.00293199,
         -0.00530183,  0.04541545, -0.01417798, -0.04672113,
          0.04091883, -0.00824805],
        [-0.04248479,  0.02341903, -0.01011783,  0.00293199,
         -0.00530183,  0.04541545, -0.01417798, -0.04672113,
          0.04091883, -0.00824805],
        [-0.04248479,  0.02341903, -0.01011783,  0.00293199,
         -0.00530183,  0.04541545, -0.01417798, -0.04672113,
          0.04091883, -0.00824805],
        [-0.04248479,  0.02341903, -0.01011783,  0.00293199,
         -0.00530183,  0.04541545, -0.01417798, -0.04672113,
          0.04091883, -0.00824805],
        [ 0.01114023,  0.02566209,  0.0469125 ,  0.0364008 ,
         -0.03960655,  0.04537593, -0.02932036, -0.02881914,
          0.03830921,  0.00631834],
        [-0.00435377,  0.01614615, -0.00484897, -0.04276036,
         -0.04298566, -0.04001956,  0.0355022 ,  0.01961042,
          0.03253317,  0.01644206],
        [-0.02514681, -0.01646106, -0.02072427,  0.0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 7874, 5452, 4540, 1835], dtype=int32)

In [23]:
# Correct way to pass a single sample
model.predict(np.expand_dims(embedded_docs[0], axis=0))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step


array([[[-0.00075445,  0.0045021 ,  0.00498869, -0.01266254,
          0.0225763 , -0.01449273,  0.01705695,  0.04024602,
          0.01606173,  0.02439729],
        [-0.00075445,  0.0045021 ,  0.00498869, -0.01266254,
          0.0225763 , -0.01449273,  0.01705695,  0.04024602,
          0.01606173,  0.02439729],
        [-0.00075445,  0.0045021 ,  0.00498869, -0.01266254,
          0.0225763 , -0.01449273,  0.01705695,  0.04024602,
          0.01606173,  0.02439729],
        [-0.00075445,  0.0045021 ,  0.00498869, -0.01266254,
          0.0225763 , -0.01449273,  0.01705695,  0.04024602,
          0.01606173,  0.02439729],
        [-0.02478722,  0.04413885, -0.04546126,  0.03826692,
         -0.01794904,  0.01859373, -0.02628509,  0.04932115,
          0.02669359,  0.02792988],
        [-0.01541324, -0.02447312, -0.01587361,  0.00699831,
          0.04532954, -0.01950389,  0.01662817, -0.0219141 ,
          0.0172363 ,  0.04390382],
        [-0.04588989,  0.02025947, -0.04828463, -0.0